function spec = estimate_ckm_wedges_skeleton(sim_data, params, options)
%ESTIMATE_CKM_WEDGES_SKELETON Scaffold for CKM-style wedge estimation.
%
% The target estimator should use only prototype-economy observables, not the
% true uncertainty states from the data-generating model. This file pins down
% the intended state-space structure before implementing the Kalman/filtering
% and likelihood pieces.

if nargin < 1
    sim_data = [];
end

if nargin < 2
    params = struct();
end

if nargin < 3
    options = struct();
end

spec = struct();
spec.status = 'scaffold_only';
spec.description = ['CKM-style BCA estimator for simulated data from an ', ...
    'RBC model with TFP stochastic volatility.'];

spec.observables = {'log_y', 'log_c', 'log_x', 'log_l'};
spec.required_levels = {'y', 'c', 'x', 'l', 'k'};
spec.wedge_states = {'log_A', 'G_share', 'tau_l', 'tau_x'};

spec.transition = ...
    's_{t+1} = mu + P s_t + eta_{t+1},  s_t = [log_A, G, tau_l, tau_x]''';
spec.measurement = ['Observables are generated by the prototype economy ', ...
    'given the latent wedges. The final estimator should solve/filter the ', ...
    'prototype model rather than use true TFP or volatility states.'];

spec.todo = { ...
    'Choose wedge law of motion and shock covariance restrictions.', ...
    'Write prototype model solution conditional on wedges.', ...
    'Construct Kalman or particle filter for simulated observables.', ...
    'Estimate wedge states and innovations from y, c, x, l, k.', ...
    'Relate estimated wedge innovations/responses to eps_v in the true simulation.'};

spec.options = options;

if ~isempty(sim_data)
    spec.debug_wedges = recover_direct_wedges_debug(sim_data, params);
    spec.note = ['debug_wedges are direct measurements for sanity checks ', ...
        'and should not be interpreted as the final CKM estimates.'];
end
end
