function result = estimate_ckm_wedges_likelihood(sim_table, prototype_params, options)
%ESTIMATE_CKM_WEDGES_LIKELIHOOD Recover wedges with a CKM-style Kalman smoother.
%
% This is a first-pass full-likelihood implementation for the preliminary
% FVGQ exercise. It follows the Dynare CKM example's linear-smoother logic:
% the three wedges {z, tau_l, tau_x} are latent states in a linearized
% prototype model. Initial transition parameters are fit from the true
% Inside-Dynare wedge observables generated by the FVGQ DGP.

    if nargin < 3
        options = struct();
    end

    defaults = struct( ...
        'force_recompile', false, ...
        'validate_shock_refresh', true, ...
        'verbose', true);
    options = merge_structs(defaults, options);

    if ~istable(sim_table)
        error('estimate_ckm_wedges_likelihood:bad_input', ...
              'sim_table must be a table with the FVGQ Experiment 1 sample.');
    end
    required_vars = {'y', 'cspt', 'ivst', 'labor', ...
                     'wedge_A', 'wedge_G', 'wedge_l', 'wedge_x'};
    missing_vars = setdiff(required_vars, sim_table.Properties.VariableNames);
    if ~isempty(missing_vars)
        error('estimate_ckm_wedges_likelihood:missing_wedges', ...
              ['Missing Inside-Dynare wedge columns: %s. ', ...
               'Rerun run_fvgq2020_simulation after updating fvgq2020_solveonly.mod.'], ...
              strjoin(missing_vars, ', '));
    end

    root_dir = fileparts(fileparts(mfilename('fullpath')));
    dynare_dir = fullfile(root_dir, 'dynare');
    output_dir = fullfile(root_dir, 'output');
    datafile = fullfile(output_dir, 'ckm_three_wedge_exp1_data.mat');
    params_file = fullfile(dynare_dir, 'ckm_three_wedge_likelihood_params.mat');

    Y = sim_table.y;
    C = sim_table.cspt;
    I = 0.06 * sim_table.ivst;
    L = sim_table.labor;

    T = height(sim_table);
    proxy_wedges = table( ...
        (1:T)', ...
        sim_table.wedge_A, ...
        sim_table.wedge_G, ...
        sim_table.wedge_l, ...
        sim_table.wedge_x, ...
        'VariableNames', {'t', 'log_A', 'G_share', 'tau_l', 'tau_x'});
    state_proxy = [sim_table.wedge_A, sim_table.wedge_l, sim_table.wedge_x];

    var_params = fit_var1(state_proxy);
    params = build_dynare_params(var_params, prototype_params);
    save(params_file, 'params');

    y = log(Y);
    c = log(C);
    x = log(I);
    l = log(L);
    save(datafile, 'y', 'c', 'x', 'l');

    refresh_diagnostics = run_dynare_model( ...
        dynare_dir, params, options.force_recompile, options.validate_shock_refresh);

    global M_ oo_ options_ bayestopt_ estim_params_
    options_.datafile = datafile;
    options_.nobs = numel(y);
    options_.first_obs = 1;
    options_.prefilter = 0;
    options_.loglinear = 0;

    clear evaluate_smoother
    [oo_, M_, options_, bayestopt_, ~, ~] = ...
        evaluate_smoother('calibration', [], M_, oo_, options_, bayestopt_, estim_params_);

    smoothed = table( ...
        (1:T)', ...
        oo_.SmoothedVariables.z(:), ...
        sim_table.wedge_G, ...
        oo_.SmoothedVariables.tau_l(:), ...
        oo_.SmoothedVariables.tau_x(:), ...
        'VariableNames', {'t', 'log_A', 'G_share', 'tau_l', 'tau_x'});

    result = struct();
    result.smoothed_wedges = smoothed;
    result.proxy_wedges = proxy_wedges;
    result.var1 = var_params;
    result.datafile = datafile;
    result.params_file = params_file;
    result.model_name = 'ckm_three_wedge_likelihood';
    result.refresh_diagnostics = refresh_diagnostics;
    result.notes = [ ...
        "Three-wedge linear CKM smoother using Dynare calib_smoother.", ...
        "State-transition parameters are initialized from Inside-Dynare DGP wedges.", ...
        "G_share is copied from the Inside-Dynare resource wedge observable."];

    if options.verbose
        fprintf(['CKM likelihood smoother complete: std(DGP tau_x)=%.4e, ', ...
                 'std(smoothed tau_x)=%.4e\n'], ...
                std(proxy_wedges.tau_x, 'omitnan'), std(smoothed.tau_x, 'omitnan'));
    end
end

function refresh_diagnostics = run_dynare_model(dynare_dir, params, force_recompile, validate_shock_refresh)
    persistent compiled_once

    addpath(dynare_dir);

    if isempty(compiled_once) || force_recompile || ~is_target_model_loaded()
        old_dir = pwd;
        cleanup = onCleanup(@() cd(old_dir));
        cd(dynare_dir);
        dynare ckm_three_wedge_likelihood.mod noclearall;
        compiled_once = true;
    end

    refresh_diagnostics = refresh_dynare_solution(params, validate_shock_refresh);
end

function refresh_diagnostics = refresh_dynare_solution(params, validate_shock_refresh)
    global M_ oo_ options_

    assert_target_model_loaded();
    apply_dynare_params(params);
    refresh_dynare_shocks(params);
    [oo_.steady_state, M_.params, steady_check] = ...
        ckm_three_wedge_likelihood_steadystate( ...
            oo_.steady_state, oo_.exo_steady_state, M_, options_);
    if steady_check
        error('estimate_ckm_wedges_likelihood:steady_state_failed', ...
              'Failed to compute CKM likelihood steady state after parameter refresh.');
    end

    var_list_ = {};
    [info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);
    if stoch_simul_failed(info)
        error('estimate_ckm_wedges_likelihood:stoch_simul_failed', ...
              'Failed to refresh CKM likelihood decision rules after parameter update.');
    end

    refresh_diagnostics = current_shock_diagnostics(params);
    if validate_shock_refresh && ...
            (refresh_diagnostics.max_sigma_diff > 1e-12 || ...
             refresh_diagnostics.max_correlation_diff > 1e-12)
        error('estimate_ckm_wedges_likelihood:shock_refresh_mismatch', ...
              ['Dynare shock covariance refresh mismatch: max |Sigma diff| = %.3e, ', ...
               'max |Corr diff| = %.3e.'], ...
              refresh_diagnostics.max_sigma_diff, ...
              refresh_diagnostics.max_correlation_diff);
    end
end

function apply_dynare_params(params)
    global M_

    dynare_param_names = dynare_names_to_cell(M_.param_names);
    fields = fieldnames(params);
    for ii = 1:numel(fields)
        idx = find(strcmp(dynare_param_names, fields{ii}), 1);
        if isempty(idx)
            error('estimate_ckm_wedges_likelihood:unknown_param', ...
                  'Parameter %s is not present in the Dynare likelihood model.', ...
                  fields{ii});
        end
        M_.params(idx) = params.(fields{ii});
    end
end

function refresh_dynare_shocks(params)
    global M_

    [sigma_e, corr_matrix] = expected_shock_matrices(params);
    M_.Sigma_e = sigma_e;
    M_.Correlation_matrix = corr_matrix;
end

function diagnostics = current_shock_diagnostics(params)
    global M_

    [expected_sigma_e, expected_corr] = expected_shock_matrices(params);
    diagnostics = struct();
    diagnostics.expected_sigma_e = expected_sigma_e;
    diagnostics.expected_correlation_matrix = expected_corr;
    diagnostics.sigma_e = M_.Sigma_e;
    diagnostics.correlation_matrix = M_.Correlation_matrix;
    diagnostics.max_sigma_diff = max(abs(M_.Sigma_e - expected_sigma_e), [], 'all');
    diagnostics.max_correlation_diff = max(abs(M_.Correlation_matrix - expected_corr), [], 'all');
end

function [sigma_e, corr_matrix] = expected_shock_matrices(params)
    sigma_vec = [params.sigma_z; params.sigma_tau_l; params.sigma_tau_x];
    corr_matrix = eye(3);
    corr_matrix(1, 2) = params.corr_z_tau_l;
    corr_matrix(2, 1) = corr_matrix(1, 2);
    corr_matrix(1, 3) = params.corr_z_tau_x;
    corr_matrix(3, 1) = corr_matrix(1, 3);
    corr_matrix(2, 3) = params.corr_tau_l_tau_x;
    corr_matrix(3, 2) = corr_matrix(2, 3);
    sigma_e = diag(sigma_vec) * corr_matrix * diag(sigma_vec);
end

function assert_target_model_loaded()
    global M_

    if ~is_target_model_loaded()
        error('estimate_ckm_wedges_likelihood:wrong_dynare_model', ...
              ['The loaded Dynare globals do not match ckm_three_wedge_likelihood. ', ...
               'Force a recompile before refreshing the solution.']);
    end
end

function tf = is_target_model_loaded()
    global M_

    tf = isstruct(M_) && isfield(M_, 'fname') && ...
        strcmp(M_.fname, 'ckm_three_wedge_likelihood');
end

function failed = stoch_simul_failed(info)
    if isnumeric(info)
        failed = any(info(:) ~= 0);
    elseif isstruct(info) && isfield(info, 'exit_flag')
        failed = info.exit_flag ~= 0;
    elseif isstruct(info) && isfield(info, 'code')
        failed = info.code ~= 0;
    else
        failed = false;
    end
end

function names = dynare_names_to_cell(raw_names)
    if iscell(raw_names)
        names = cellfun(@strtrim, raw_names(:), 'UniformOutput', false);
    elseif isstring(raw_names)
        names = cellstr(strtrim(raw_names(:)));
    else
        names = cellstr(strtrim(raw_names));
    end
end

function var_params = fit_var1(state_proxy)
    x_lag = state_proxy(1:end-1, :);
    x_now = state_proxy(2:end, :);
    X = [ones(size(x_lag, 1), 1), x_lag];
    B = X \ x_now;
    resid = x_now - X * B;

    transition = B(2:end, :)';
    mean_state = mean(state_proxy, 1)';
    spectral_radius = max(abs(eig(transition)));
    if spectral_radius >= 0.995
        transition = transition * (0.99 / spectral_radius);
    end
    % Preserve the fitted long-run mean in the stationary VAR approximation.
    intercept = (eye(size(transition)) - transition) * mean_state;
    covariance = cov(resid, 1);
    covariance = nearest_spd(covariance + 1e-8 * eye(3));

    var_params = struct();
    var_params.intercept = intercept;
    var_params.transition = transition;
    var_params.covariance = covariance;
    var_params.mean_state = mean_state;
end

function params = build_dynare_params(var_params, prototype_params)
    params = struct();
    params.beta = prototype_params.beta;
    params.alpha = prototype_params.alpha;
    params.chi = prototype_params.chi;
    params.delta = prototype_params.delta;
    params.gamma = prototype_params.gamma;
    params.nu = prototype_params.nu;

    P = var_params.transition;
    P0 = var_params.intercept;
    Sigma = var_params.covariance;
    Corr = corrcov(Sigma);

    params.P0_z_bar = P0(1);
    params.rho_zz = P(1, 1);
    params.rho_zl = P(1, 2);
    params.rho_zx = P(1, 3);

    params.P0_tau_l_bar = P0(2);
    params.rho_lz = P(2, 1);
    params.rho_ll = P(2, 2);
    params.rho_lx = P(2, 3);

    params.P0_tau_x_bar = P0(3);
    params.rho_xz = P(3, 1);
    params.rho_xl = P(3, 2);
    params.rho_xx = P(3, 3);

    params.z_bar = var_params.mean_state(1);
    params.tau_l_bar = var_params.mean_state(2);
    params.tau_x_bar = var_params.mean_state(3);

    params.sigma_z = sqrt(Sigma(1, 1));
    params.sigma_tau_l = sqrt(Sigma(2, 2));
    params.sigma_tau_x = sqrt(Sigma(3, 3));
    params.corr_z_tau_l = Corr(1, 2);
    params.corr_z_tau_x = Corr(1, 3);
    params.corr_tau_l_tau_x = Corr(2, 3);
end

function A = nearest_spd(A)
    A = (A + A') / 2;
    [V, D] = eig(A);
    D = diag(max(diag(D), 1e-10));
    A = V * D * V';
    A = (A + A') / 2;
end

function out = merge_structs(defaults, overrides)
    out = defaults;
    fields = fieldnames(overrides);
    for ii = 1:numel(fields)
        out.(fields{ii}) = overrides.(fields{ii});
    end
end
